
site_name: Knowledge Base
site_url: https://ssteinbuss.github.io/knowledge-base/
repo_url: https://github.com/ssteinbuss/knowledge-base
repo_name: knowledge-base
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/IDSA-logo_2.png
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
  palette:
    primary: custom
    accent: custom
extra_css:
  - assets/styles.css
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - literate-nav:
      nav_file: SUMMARY.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - def_list
extra:
  generator: false
